name: Add PR to AxonIQ Console project

on:
  pull_request:
    types:
      - labeled

jobs:
  add-to-console-project:
    name: Add Dependency Upgrade PRs to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/AxonIQ/projects/9
          github-token: ${{ secrets.ADD_TO_CONSOLE_PROJECT_TOKEN }}
          labeled: 'Type: Dependency Upgrade'
          label-operator: AND
