name: PR - Test and Build

on:
  pull_request:

jobs:
  build:
    name: Test and Build on JDK ${{ matrix.java-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - java-version: 8
            sonar-enabled: false
          - java-version: 11
            sonar-enabled: false
          - java-version: 17
            sonar-enabled: true
          - java-version: 21
            sonar-enabled: false
      fail-fast: false # run both to the end

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3.13.0
        with:
          distribution: "zulu"
          java-version: ${{ matrix.java-version }}
          cache: "maven"
          server-id: sonatype
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Test and Build
        if: ${{ !matrix.sonar-enabled }}
        run: |
          ./mvnw -B -U -Dstyle.color=always -Possrh clean verify

      - name: Test and Build with Coverage reports
        if: matrix.sonar-enabled
        run: |
          ./mvnw -B -U -Dstyle.color=always -Possrh -Dcoverage clean verify

      - name: Sonar Analysis
        if: ${{ success() && matrix.sonar-enabled }}
        run: ./mvnw -B -Dstyle.color=always org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=AxonIQ_console-framework-client
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.CONSOLE_SONAR_TOKEN }}
